= AF_10271 - Abfrage von angereicherten PDF per Token (Rechnungsersteller)

[cols="h,1"]
|===
| ID | AF_10271
| Verbindlichkeit | nicht definiert
| Letzte Aktualisierung | 2025-05-23
| Beschreibung | Dieser +
Anwendungsfall beschreibt den Abruf eines angereicherten PDF aus dem +
Fachdienst seitens des Rechnungserstellers mittels eines Tokens, welches +
er zuvor bei der Übergabe einer Rechnung bzw. eines Dokuments vom +
Fachdienst erhalten hat.
| Vorbedingung | * Der Rechnungsersteller hat ein Nutzerkonto. +
* Der Rechnungsersteller ist autorisiert. +
* Der Rechnungsersteller verfügt über ein +
Token, welches er zuvor bei der Übergabe einer Rechnung bzw. eines +
Dokuments vom Fachdienst erhalten hat. +
* Im Fachdienst liegen die dem Token entsprechenden Daten vor (Rechnung oder Dokument).
| Ablauf | * Der Rechnungsersteller ruft das angereicherte PDF zu einer Rechnung bzw. einem Dokument aus dem Fachdienst ab. Er übergibt dazu das Token. +
* Der Fachdienst prüft, ob es zu dem Token eine Rechnung bzw. ein Dokument gibt. +
* Falls ja, wird das angereicherte PDF zurückgegeben.
| Nachbedingung | Im Erfolgsfall: +
* Der Rechnungsersteller hat das angereicherte PDF erhalten.
| Alternativen | * Im Fehlerfall wird eine Fehlermeldung zurückgegeben. +
* Der Anwendungsfall kann alternativ auch für eine Menge ("Bulk") von Token durchgeführt werden. In diesem Fall +
* werden mehrere Token übergeben und +
* pro Token entweder das angereicherte PDF - oder im Fall eines Fehlers - eine Fehlermeldung zurückgegeben.
|===
