= AF_10180 - Abfrage von Daten zu Rechnungen und Dokumenten per Token (Kostenträger)

[cols="h,1"]
|===
| ID | AF_10180
| Verbindlichkeit | nicht definiert
| Letzte Aktualisierung | 2025-05-23
| Beschreibung | Dieser +
Anwendungsfall beschreibt den Abruf von Daten aus dem Fachdienst +
seitens des Kostenträger (KTR) mittels Token zu eingereichten Rechnungen +
und/oder Dokumenten, d.h. +
* mit Token aus den Barcodes postalisch eingereichter Rechnungen/Dokumente (siehe 4.1 Einreichung per Post) +
oder +
* per Frontend geteilten Rechnungs-/Dokumententoken (siehe 4.2 Einreichung über das Frontend).
| Vorbedingung | * Der KTR (Nutzer) hat ein Nutzerkonto. +
* Der KTR ist autorisiert. +
* Der KTR hat vom Versicherten eine oder mehrere Rechnungen und ggf. ergänzende Dokumente +
* per Post erhalten und die Token durch Scannen der Barcodes ausgelesen +
oder +
* digital als Token erhalten. +
* Der Versicherte hat ein Nutzerkonto. +
* Dort liegen die dem KTR zugeschickten Rechnungen und Dokumente in digitaler Form vor.
| Ablauf | Der KTR nimmt eine Eingangsverarbeitung der eingegangenen Dokumente vor. +
Bei Rechnungen und Dokumenten mit Rechnungs-/Dokument-Token: +
* Auslesen der Token +
* Übergabe der Token an den Fachdienst, dabei Übergabe +
einer Information zu gewünschten Rückgabeformaten (strukturierte Daten, +
Original-PDF, angereichertes PDF, Signatur) +
* Der Fachdienst prüft, ob es zu jedem Token ein Dokument bzw. eine Rechnung gibt. +
* Falls ja, werden die Daten in der angeforderten Formatauswahl zurückgegeben.
| Nachbedingung | Im Erfolgsfall: +
* Der KTR hat je nach Formatauswahl die gewünschten Ausgabedaten erhalten. +
* Die Rechnungen/Dokumente wurden im FD markiert als "Vom Kostenträger abgerufen" unter Angabe von KTR und Zeitpunkt. +
Hinweis: Ziel ist es, den Vorgang der postalischen Einreichung im Fachdienst "digital abzubilden", sodass +
* im Fachdienst erfasst ist, dass die Daten durch diesen KTR bereits abgerufen wurden und für diesen nicht länger relevant sind. +
* Nutzer, die ein DiPag FdV verwenden, sehen können, dass die +
postalische Einreichung "angekommen ist", d.h. für den Einreicher +
ist die Einreichung wie eine auf anderem Weg erfolgte Einreichung +
sichtbar.
| Alternativen | Im Fehlerfall werden eine Fehlermeldung zurückgegeben und die nicht "einlösbaren" Token aufgeführt.
|===
