= AF_10140 - Automatische Anlage der individuellen Berechtigung zum Rechnungsversand

[cols="h,1"]
|===
| ID | AF_10140
| Verbindlichkeit | MUSS
| Letzte Aktualisierung | 2025-05-23
| Beschreibung | Der +
im Anwendungsfall beschriebene Vorgang dient dazu, ausgehend vom +
Versand von Rechnungen, die individuelle Berechtigung zum +
Rechnungsversand für einzelne Rechnungsersteller für den Versicherten +
sichtbar zu machen und deren Widerruf zu ermöglichen.
| Vorbedingungen | * Der Rechnungsersteller (Nutzer) hat im Rahmen des +
Behandlungsvertrags die Einwilligung des Rechnungsempfängers zum Versand +
digitaler Rechnungen erhalten. +
* Der Rechnungsempfänger (Versicherter) hat ein Nutzerkonto +
im Fachdienst. (Somit hat er generell zugestimmt, dass digitale +
Rechnungen an ihn geschickt werden dürfen.) +
* Der Rechnungsersteller hat bislang noch keine Rechnung an +
den Rechnungsempfänger geschickt. Es liegt dementsprechend noch keine +
Berechtigungsregel vor, die die individuelle Berechtigung dieses +
Rechnungserstellers zum Rechnungsversand erfasst.
| Ablauf | * Der Rechnungsersteller sendet eine Rechnung über den Fachdienst an den Rechnungsempfänger (siehe Anwendungsfälle dazu in 6.2.4 Validierung und Versand von Rechnungen und Dokumenten). +
* Dadurch wird die Anlage einer Berechtigungsregel im Fachdienst ausgelöst.
| Nachbedingungen | * Eine Berechtigungsregel wurde vom Fachdienst angelegt mit diesen Angaben: +
* Typ: "Rechnungsversand" +
* Initiator: der Rechnungsersteller +
* Bestätiger: der Rechnungsempfänger +
* Berechtigter: der Rechnungsersteller +
* Betroffener: der Rechnungsempfänger +
* Zustand: "gültig" +
* Der Rechnungsempfänger kann den Rechnungsersteller und die +
für ihn geltende individuelle Berechtigung in der +
Berechtigungsverwaltung sehen und die Berechtigung bei Bedarf bearbeiten +
(widerrufen, bestätigen).
| Alternativen | -
|===
